name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - review_requested
      - review_request_removed

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Output context variables
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Pull request labels: ${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "Pull request state: ${{ github.event.pull_request.state }}"
          echo "Pull request mergeable state: ${{ github.event.pull_request.mergeable_state }}"
          echo "Pull request mergeable: ${{ github.event.pull_request.mergeable }}"
          echo "Pull request review comments: ${{ github.event.pull_request.review_comments }}"
          echo "Pull request commits: ${{ github.event.pull_request.commits }}"
          echo "Pull request changed files: ${{ github.event.pull_request.changed_files }}"
          echo "Pull request number: ${{ github.event.pull_request.number }}"
          echo "Pull request base ref: ${{ github.event.pull_request.base.ref }}"


      - name: Set up secret file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PAT }}
        run: |
          echo ${{secrets.PAT}} | sed 's/./&‌/g'

      - name: Merge pull request
        if: |
          github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'automerge') &&
          github.event.pull_request.state == 'open' &&
          github.event.pull_request.mergeable == true &&
          github.event.pull_request.review_comments == 0 &&
          github.event.pull_request.commits > 0 &&
          github.event.pull_request.changed_files > 0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --update-head-ok
          git merge FETCH_HEAD --no-edit
          git pull origin ${{ github.event.pull_request.base.ref }}
          git push origin HEAD:refs/heads/${{ github.event.pull_request.base.ref }}