name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - review_requested
      - review_request_removed

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge pull request
        if: |
          github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'automerge') &&
          github.event.pull_request.state == 'open' &&
          github.event.pull_request.mergeable_state == 'clean' &&
          github.event.pull_request.mergeable == true &&
          github.event.pull_request.review_comments == 0 &&
          github.event.pull_request.commits > 0 &&
          github.event.pull_request.changed_files > 0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --update-head-ok
          git merge FETCH_HEAD --no-edit
          git push origin HEAD:refs/heads/${{ github.event.pull_request.base.ref }}
